<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INLEN8520065665" failures="1" tests="2" name="Error validation  Test" time="24.775" errors="0" timestamp="2024-07-08T11:55:10 IST">
  <testcase classname="Selenium_Framework.Test.ErrorValidations" name="LoginErrorValidation" time="1.747"/>
  <testcase classname="Selenium_Framework.Test.ErrorValidations" name="ProductErrorValidation" time="13.82">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Selenium_Framework.Test.ErrorValidations.ProductErrorValidation(ErrorValidations.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- ProductErrorValidation -->
</testsuite> <!-- Error validation  Test -->
